kind: Service
apiVersion: v1
metadata:
  name: jenkins-ubuntu-slave-svc # when u communicate with the slave through the service (Host)
  namespace: jenkins
spec:
  selector:
    app: jenkins-ubuntu-slave
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22